
import java.awt.Frame;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.JDialog;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;




/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Eyüp Albayrak
 */
public class ogrencikitapekranı extends javax.swing.JFrame {
    
    DefaultTableModel model;
    ogrenci_islemleri islemler ;

    /**
     * Creates new form ogrencikitapekranı
     * @param parent
     * @param modal
     */
    public ogrencikitapekranı(Frame parent, boolean modal) {
        try {
            islemler = new ogrenci_islemleri();
            initComponents();
            model = (DefaultTableModel)kitaptablosu.getModel();
            kitaplarigoster();
        }catch (SQLException ex) {
            System.out.println("veritabanına baglanılamadı");
        }
        
    }

    ogrencikitapekranı() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        kitaptablosu = new javax.swing.JTable();
        arama_cubugu = new javax.swing.JTextField();
        isimgirmealanı = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        yazi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(400, 400, 0, 0));
        setLocation(new java.awt.Point(400, 300));

        kitaptablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "İd", "Kitapın Adı", "Kitapın Yazarı", "Kitapın Türü"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        kitaptablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kitaptablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(kitaptablosu);
        if (kitaptablosu.getColumnModel().getColumnCount() > 0) {
            kitaptablosu.getColumnModel().getColumn(0).setResizable(false);
            kitaptablosu.getColumnModel().getColumn(1).setResizable(false);
            kitaptablosu.getColumnModel().getColumn(2).setResizable(false);
            kitaptablosu.getColumnModel().getColumn(3).setResizable(false);
        }

        arama_cubugu.setText("Ödünç Almak İstediginiz Kitabı Seciniz");
        arama_cubugu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arama_cubuguMouseClicked(evt);
            }
        });
        arama_cubugu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arama_cubuguActionPerformed(evt);
            }
        });
        arama_cubugu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                arama_cubuguKeyReleased(evt);
            }
        });

        isimgirmealanı.setText("Kullanıcı Adınızı Giriniz:");
        isimgirmealanı.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                isimgirmealanıMouseClicked(evt);
            }
        });
        isimgirmealanı.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isimgirmealanıActionPerformed(evt);
            }
        });

        jButton1.setText("Ödünç Al");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Geri");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        yazi.setForeground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(yazi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(arama_cubugu, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(isimgirmealanı, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(isimgirmealanı, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(arama_cubugu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yazi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void arama_cubuguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arama_cubuguActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arama_cubuguActionPerformed
    public void dinamikAra(String ara){
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        kitaptablosu.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(ara));
    }
    private void arama_cubuguKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arama_cubuguKeyReleased
        String ara =arama_cubugu.getText();
        dinamikAra(ara);
        
    }//GEN-LAST:event_arama_cubuguKeyReleased
    /*    */
    private void kitaptablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kitaptablosuMouseClicked
        arama_cubugu.setText("");
        int secili_row = kitaptablosu.getSelectedRow();
        arama_cubugu.setText(model.getValueAt(secili_row, 1).toString());
    }//GEN-LAST:event_kitaptablosuMouseClicked

    private void isimgirmealanıMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isimgirmealanıMouseClicked
        isimgirmealanı.setText("");
    }//GEN-LAST:event_isimgirmealanıMouseClicked

    private void isimgirmealanıActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isimgirmealanıActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isimgirmealanıActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if("Kullanıcı Adınızı Giriniz:".equals(isimgirmealanı.getText()) ){
            yazi.setText("");
            yazi.setText("Lütfen Kullanıcı Adınızı Giriniz");
            
        }
        else if("Ödünç Almak İstediginiz Kitabı Seciniz".equals(arama_cubugu.getText()) ){
            
            yazi.setText("Lütfen Kitap Seçiniz");
        }
        else{
        yazi.setText("");
        String kitap = arama_cubugu.getText();
        String ad = isimgirmealanı.getText();
        try {
            islemler.ödüncalekle(ad, kitap);
            arama_cubugu.setText("");
            isimgirmealanı.setText("");
            yazi.setText("Kitap Ödünç Alındı");
        } catch (SQLException ex) {
            Logger.getLogger(ogrencikitapekranı.class.getName()).log(Level.SEVERE, null, ex);
        }}
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void arama_cubuguMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arama_cubuguMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_arama_cubuguMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ogrencisecimekranı ogrencisecimekranı4 = new ogrencisecimekranı();
        ogrencisecimekranı4.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    public void kitaplarigoster(){
        model.setRowCount(0);
        ArrayList<kitap> kitaplar = islemler.kitaplarıgetir();
        if(kitaplar != null){
            for(kitap kitap :kitaplar){
                Object[] eklenecek = {kitap.getId(),kitap.getAd(),kitap.getYazar(),kitap.getTür()};
                model.addRow(eklenecek);
            }
        }
                
    }
    
    public static void main(String args[]) {
        

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ogrencikitapekranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ogrencikitapekranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ogrencikitapekranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ogrencikitapekranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        new ogrencikitapekranı(new javax.swing.JFrame(), true).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arama_cubugu;
    private javax.swing.JTextField isimgirmealanı;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable kitaptablosu;
    private javax.swing.JLabel yazi;
    // End of variables declaration//GEN-END:variables

}
